### PR TITLE
proxy: Avoid sorting endpoints for every request

### LINKED ISSUE #4497: proxy unstable routing behavior for routes that match multiple rules
Turns out that the config changes in #4461 cause some unstable behavior for routes that match multiple rules :scream:. E.g. we have:

```
                {                                 
                    Endpoint:    "/app/list",
                    Backend:     "http://localhost:9140",
                    Unprotected: true,
                },
                {
                    Endpoint: "/app/", // /app or /apps? ocdav only handles /apps
                    Backend:  "http://localhost:9140",
                },
```

And now requests on `/app/list/` sometimes go through and sometimes fail. (Not this is not exactly a new bug in the code, it just seems that we didn't have overlapping rules of the same type before. I'll open a new issue for that and try to come up with a quick fix. (We might also temporary revert this PR).

_Originally posted by @rhafer in https://github.com/owncloud/ocis/issues/4461#issuecomment-1234328011_

### PR DESCRIPTION
**Pull request by rhafer**
## Description
The endpoints are no longer hashed by path name in the directors map since that made iterating over the endpoints unstable. They are now stored in a slice in the order in which the are defined in the configuration.

This also includes a fix to make the archiver work for public-links (https://github.com/owncloud/ocis/pull/4461#pullrequestreview-1093104888)

## Related Issue
- Fixes  #4497

### CODE REVIEW

File: services/proxy/pkg/router/router.go [hunk 1]
```diff
@@ -207,32 +209,27 @@ func (rt Router) Route(r *http.Request) (RoutingInfo, bool) {
...
-				return rt.directors[pol][rtype][method][endpoint], true
+				rt.logger.Error().Str("endpoint", ri.endpoint).Msg("match")
+				return ri, true
 			}
 		}
 	}
 
 	// override default director with root. If any
-	if ri, ok := rt.directors[pol][config.PrefixRoute][method]["/"]; ok { // try specific method
+	if ri := rt.directors[pol][config.PrefixRoute][method][0]; ri.endpoint == "/" { // try specific method
```
Comment (rhafer) [inline services/proxy/pkg/router/router.go:230]: I am still not too happy with this. I guess I need something better here for the fallback/default routes.

**Review by kulmann — COMMENTED** [review]
I thought about my comment about the archiver again, and actually I'm confused here. oC Web always adds the `public-token` to the url query (on any public link), so the public token auth provider should be used in the authentication middleware... and fails? Might just be a bug in the auth provider. The route should not be unprotected, as I thought initially. Does that sound reasonable? 🤔

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiArchiver-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/15217/42/1) failed. Further test are cancelled...

**Comment by rhafer** [comment]
> I thought about my comment about the archiver again, and actually I'm confused here. oC Web always adds the `public-token` to the url query (on any public link), so the public token auth provider should be used in the authentication middleware... and fails? Might just be a bug in the auth provider. The route should not be unprotected, as I thought initially. Does that sound reasonable? 

Yes. That's what I also found out while looking at the code. And it's exactly what this commit (https://github.com/owncloud/ocis/pull/4514/commits/6bbdcc2e3237f8dc1c8116dda35288b1dcc9c730) implements. IIUC the  `_publicPaths` slice contains a list of paths which are enabled for the public token auth provider. I.e. "public token auth" only works for paths listed there. And `/archiver` was simply missing. (This change does not make the archiver unprotected)

**Comment by rhafer** [comment]
Hm, this seems to break the archiver somehow:-( (https://drone.owncloud.com/owncloud/ocis/15224/42/8)

**Comment by kulmann** [comment]
> > I thought about my comment about the archiver again, and actually I'm confused here. oC Web always adds the `public-token` to the url query (on any public link), so the public token auth provider should be used in the authentication middleware... and fails? Might just be a bug in the auth provider. The route should not be unprotected, as I thought initially. Does that sound reasonable?
> 
> Yes. That's what I also found out while looking at the code. And it's exactly what this commit ([6bbdcc2](https://github.com/owncloud/ocis/commit/6bbdcc2e3237f8dc1c8116dda35288b1dcc9c730)) implements. IIUC the `_publicPaths` slice contains a list of paths which are enabled for the public token auth provider. I.e. "public token auth" only works for paths listed there. And `/archiver` was simply missing. (This change does not make the archiver unprotected)

Ah, makes sense, thanks for explaining :heart:

**Comment by C0rby** [comment]
You need to rebase from master and then the `go generate` steps should work again.

**Review by C0rby — APPROVED** [review]
I think the whole proxy code is not ideal but this is good for now. :+1:
