### PR TITLE
proxy: Return an error when autoprovision a user fails

### LINKED ISSUE #6194: Autoprovisioning user failed with panic for some users
## Describe the bug

While using oauth, one user is autoprovisioned correctly and can log in, while another is stuck on a "You were automatically logged out for security reasons" loop. See logs below.

## Steps to reproduce

Unclear. Autoprovisioning fails for user with username `0x1a8510f2` but succeeds for username `l1qu1d`. No other significant differences between the users.

## Expected behavior
The user is autoprovisioned and signed in correctly.

## Actual behavior
The user is presented with the following screen, and errors appear in logs:

image

```
2023-04-30T11:42:58.151643208Z ERR Error creating user | service=proxy error=400 Bad Request
2023-04-30T11:42:58.151657188Z ERR Autoprovisioning user failed | service=proxy error=400 Bad Request
2023/04/30 11:42:58 http: panic serving 172.125.0.200:32796: runtime error: invalid memory address or nil pointer dereference
goroutine 358401 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1854 +0xbf
panic({0x3d91600, 0x5a40c60})
	runtime/panic.go:890 +0x263
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.accountResolver.ServeHTTP({{0x42700e0, 0xc001ccc6c0}, {{{0x427f110, 0xc0014a1850}, 0x3, {0x0, 0x0}, {0xc001948400, 0x12, 0x1f4}, ...}}, ...}, ...)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/account_resolver.go:82 +0x575
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.Authentication.func1.1({0x7f480f6cb358, 0xc000e53140}, 0xc0000c1300)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/authentication.go:64 +0x1fa
net/http.HandlerFunc.ServeHTTP(0x428bf08?, {0x7f480f6cb358?, 0xc000e53140?}, 0x5cf8e40?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/router.Middleware.func1.1({0x7f480f6cb358, 0xc000e53140}, 0xc0000c1200)
	github.com/owncloud/ocis/v2/services/proxy/pkg/router/router.go:31 +0x205
net/http.HandlerFunc.ServeHTTP(0xc000779ce4?, {0x7f480f6cb358?, 0xc000e53140?}, 0xc001aa9730?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.OIDCWellKnownRewrite.func1.1({0x7f480f6cb358, 0xc000e53140}, 0xc0000c1200?)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/oidc_well-known.go:45 +0x313
net/http.HandlerFunc.ServeHTTP(0xc0094f7140?, {0x7f480f6cb358?, 0xc000e53140?}, 0xc71ea5?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.HTTPSRedirect.func1({0x7f480f6cb358, 0xc000e53140}, 0xc0000c1200)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/https_redirect.go:17 +0x142
net/http.HandlerFunc.ServeHTTP(0x4289a30?, {0x7f480f6cb358?, 0xc000e53140?}, 0xc0000c1200?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.AccessLog.func1.1({0x4289a30, 0xc00140cee0}, 0xc0000c1200)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:17 +0xc8
net/http.HandlerFunc.ServeHTTP(0x428be60?, {0x4289a30?, 0xc00140cee0?}, 0x39fd198?)
	net/http/server.go:2122 +0x2f
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x4289a30, 0xc00140cee0}, 0xc0000c1100)
	github.com/go-chi/chi/v5@v5.0.8/middleware/request_id.go:76 +0x22d
net/http.HandlerFunc.ServeHTTP(0xc0000c1100?, {0x4289a30?, 0xc00140cee0?}, 0xc000094c00?)
	net/http/server.go:2122 +0x2f
github.com/go-chi/chi/v5/middleware.RealIP.func1({0x4289a30, 0xc00140cee0}, 0xc0000c1100)
	github.com/go-chi/chi/v5@v5.0.8/middleware/realip.go:36 +0x9e
net/http.HandlerFunc.ServeHTTP(0x57080b?, {0x4289a30?, 0xc00140cee0?}, 0x428b350?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/ocis-pkg/middleware.TraceContext.func1({0x4289a30, 0xc00140cee0}, 0xc0000c0f00)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/tracing.go:19 +0x184
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4289a30?, 0xc00140cee0?}, 0x46f9d0?)
	net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xc0094f7110?}, {0x4289a30, 0xc00140cee0}, 0xc0000c0f00)
	net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0091477a0, {0x428bf08, 0xc0017c4d20})
	net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x5ed
```

## Setup

<details>
<p>

Fresh installation via docker using `owncloud/ocis:latest` updated today.

image

Caddy proxy in front of container with the following config:

```
files.l1qu1d.net {
        import tls
        import sec
        import log

        # Compression
        encode zstd gzip

        reverse_proxy * {
                to https://ocis:9200
                transport http {
                        tls_insecure_skip_verify
                }
        }
}
```

Auth handled by ZITADEL with the following config:

image
image

</p>
</details>

### PR DESCRIPTION
**Pull request by rhafer**
Fixes #6194

### CODE REVIEW

File: services/graph/pkg/config/config.go [hunk 1]
```diff
@@ -104,7 +104,7 @@ type Identity struct {
 // API represents API configuration parameters.
 type API struct {
 	GroupMembersPatchLimit int    `yaml:"group_members_patch_limit" env:"GRAPH_GROUP_MEMBERS_PATCH_LIMIT" desc:"The amount of group members allowed to be added with a single patch request."`
-	UsernameMatch          string `yaml:"graph_username_match" env:"GRAPH_USERNAME_MATCH" desc:"Option to allow legacy usernames. Supported options are 'default' and 'none'."`
+	UsernameMatch          string `yaml:"graph_username_match" env:"GRAPH_USERNAME_MATCH" desc:"Which restrictions should be applied to usernames. Supported options are 'default' and 'none'. When set to 'default' user names must not start with a number and are restricted to ASCII characters. When set to 'none', no restrictions are applied. The default value is 'default'"`
```
Comment (mmattel) [inline services/graph/pkg/config/config.go:107]:
```suggestion
	UsernameMatch          string `yaml:"graph_username_match" env:"GRAPH_USERNAME_MATCH" desc:"Apply restrictions to usernames. Supported values are 'default' and 'none'. When set to 'default', user names must not start with a number and are restricted to ASCII characters. When set to 'none', no restrictions are applied. The default value is 'default'."`
```

**Comment by mmattel** [comment]
It would be good to have a note in the graph readme to tell that one can restrict namings of usernames. Finding this setting is, as the referenced issue shows a challenge.

**Review by kobergj — APPROVED** [review]

**Comment by rhafer** [comment]
> It would be good to have a note in the graph readme to tell that one can restrict usernames.

Agreed. But that would require adding at least some basic section which outlines the user/group management capabilities of the `graph` service. Just adding a note about 'GRAPH_USERNAME_MATCH' without more context won't help much.

I think that is beyond the scope of this PR, which tries to address a somewhat serious issue.

Please, open a new issue, feel free to assign it to me and I'll happily provide content about the user management settings in a separate PR.
