### PR TITLE
fix issue ocis-1043 in settings service

### LINKED ISSUE #1043: Settings menu item in app switcher and user menu
The settings menu item is supposed to be placed in the `user` menu (click on your name in the top right to see it). However, when the settings UI is the active extension (i.e. you navigated into it), there are two menu items for the settings:
- One in the user menu (where it should be)
- Another one in the app switcher (that shouldn't exist)

Going back to another extension reverts this, so that the settings menu item is only in the user menu again.

### PR DESCRIPTION
**Pull request by fschade**
partially fixes #1043

### CODE REVIEW

File: settings/ui/components/SettingsApp.vue [hunk 1]
```diff
@@ -107,8 +108,8 @@ export default {
     getExtensionName (extension) {
       extension = extension || ''
       switch (extension) {
-        case 'ocis-accounts': return this.$gettext('Account')
-        case 'ocis-hello': return this.$gettext('Hello')
+        case 'ocis-accounts': return 'Account'
```
Comment (kulmann) [inline settings/ui/components/SettingsApp.vue:111]: The `this.$gettext` is needed. Otherwise the strings will not be extracted for translation (submission to transifex).

**Review by kulmann — CHANGES_REQUESTED** [review]

File: settings/ui/components/SettingsApp.vue [hunk 2]
```diff
@@ -15,32 +15,33 @@
...
-            <hr />
+            <hr/>
           </template>
           <template v-if="settingsValuesLoaded">
             <settings-bundle
-              v-for="bundle in selectedBundles"
-              :key="'bundle-' + bundle.id"
-              :bundle="bundle"
-              class="oc-mt"
+                v-for="bundle in selectedBundles"
```
Comment (kulmann) [inline settings/ui/components/SettingsApp.vue:22]: The indentation looks wrong here and in the next three lines 🤔

File: settings/ui/components/SettingsApp.vue [hunk 3]
```diff
@@ -118,21 +122,30 @@ export default {
...
-    this.resetMenuItems()
-    this.resetSelectedExtension()
+  created () {
+    this.initialize()
   },
   watch: {
-    initialized () {
-      this.resetMenuItems()
-      this.resetSelectedExtension()
+    '$language.current': {
```
Comment (kulmann) [inline settings/ui/components/SettingsApp.vue:138]: I fear that this is needed for now. But it looks wrong that extensions have to watch on the language themselves. Only oC web core should be responsible for triggering translation updates on language changes. 🤔

File: settings/ui/components/SettingsApp.vue (hunk 2 above)
Comment (fschade) [reply settings/ui/components/SettingsApp.vue:22]: dang, my formatter haven't picked this up... done in new commit.

File: settings/ui/components/SettingsApp.vue (hunk 3 above)
Comment (fschade) [reply settings/ui/components/SettingsApp.vue:141]: yea, no separation of concerns. I pick thist up for our improvement paper

**Review by kulmann — APPROVED** [review]
👍
