### PR TITLE
Try to fix problems with unescaping values.

### LINKED ISSUE #5083: Group having percentage (%) can be created but cannot be GET
## Describe the bug

A group having only `%` as a special character in its name can be created but cannot GET it.

**NOTE**: but if the group name has more other special characters then GET request works
For Example:
`50%pass` -> GET fails :x:
`50%pass+pass` -> GET works :heavy_check_mark: 

## Steps to reproduce

1. Create a group with % in its name
```bash
 curl -XPOST "https://localhost:9200/graph/v1.0/groups" -d'{"displayName":"50%pass"}' -uadmin:admin -vk
```
```bash
< HTTP/1.1 200 OK
< Content-Length: 70
< Content-Type: application/json; charset=utf-8
< Date: Mon, 21 Nov 2022 04:57:06 GMT
< X-Graph-Version: 2.0.0-rc.1+1329daffc
< 
{
  "displayName": "50%pass",
  "id": "e643c421-ff19-44fa-839d-9e419889441d"
}
```
2. try to GET the group (`url encoded groupname`)
```bash
curl "https://host.docker.internal:9200/graph/v1.0/groups/50%25pass" -uadmin:admin -vk
```

## Expected behavior
to GET group details

## Actual behavior
400 bad request
```bash
< HTTP/1.1 400 Bad Request
< Content-Length: 322
< Content-Type: application/json; charset=utf-8
< Date: Mon, 21 Nov 2022 04:57:49 GMT
< X-Graph-Version: 2.0.0-rc.1+1329daffc
< 
{
  "error": {
    "code": "invalidRequest",
    "innererror": {
      "date": "2022-11-21T04:57:49Z",
      "request-id": "cc648ecd9a72/vFtv8pfDzE-001490"
    },
    "message": "unescaping group id failed"
  }
}
{
  "error": {
    "code": "invalidRequest",
    "innererror": {
      "date": "2022-11-21T04:57:49Z",
      "request-id": "cc648ecd9a72/vFtv8pfDzE-001490"
    },
    "message": "missing group id"
  }
}
```

## Setup

Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Excds**
Overwriting URL.RawPath with EscapedPath to avoid problems with unescaping values.

Fixes #5083

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>localApiTests-apiGraph-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/21465/51/1) failed. Further test are cancelled...

**Comment by rhafer** [comment]
This is looking good:

```
runsh: There were no unexpected failures.
runsh: Total unexpected passed scenarios throughout the test run:
apiGraph/deleteGroup.feature:49
apiGraph/deleteGroup.feature:50
apiGraph/deleteGroup.feature:51
apiGraph/editGroup.feature:25
```

@Excds Seems we can remove some items from the expected failures list ;-)

File: services/graph/pkg/service/v0/graph.go [hunk 1]
```diff
@@ -76,6 +76,9 @@ type Graph struct {
 
 // ServeHTTP implements the Service interface.
 func (g Graph) ServeHTTP(w http.ResponseWriter, r *http.Request) {
+	// Adding this as a fix for some weird unescaping issues we've had.
```
Comment (rhafer) [inline services/graph/pkg/service/v0/graph.go:79]: Could you please add some more info here what the issue actually is. (With a link to the chi-router github issue?)

**Review by rhafer — CHANGES_REQUESTED** [review]

File: services/graph/pkg/service/v0/graph.go (hunk 1 above)
Comment (rhafer) [reply services/graph/pkg/service/v0/graph.go:79]: Also: I think this fixes some open issue(s), could you please mention them with `Fixes: <#issue>` in the commit message?

Comment (Excds) [reply services/graph/pkg/service/v0/graph.go]: Ah, yes, should have done that. Fixed now.

**Review by rhafer — APPROVED** [review]
