### PR TITLE
[tests-only][full-ci] retry requests for Given steps on 409 response code

### LINKED ISSUE #6630: API tests fail Intermittently on `coreApiWebdavMove1/moveFolder.feature`
Build fail: https://drone.owncloud.com/owncloud/ocis/23650/65/5 , https://drone.owncloud.com/owncloud/ocis/24195/65/5
Hints: If reproducing locally is hard then try to understand the code and error  thrown and make assumption with strong logic what could cause this issue to occur in CI only 
```
Scenario Outline: renaming folder with dots in the path                                                                         # /drone/src/tests/acceptance/features/coreApiWebdavMove1/moveFolder.feature:105
    Given using <dav_version> DAV path                                                                                            # FeatureContext::usingOldOrNewDavPath()
    And user "Alice" has created folder "<folder_name>"                                                                           # FeatureContext::userHasCreatedFolder()
    And user "Alice" has uploaded file with content "uploaded content for file name ending with a dot" to "<folder_name>/abc.txt" # FeatureContext::userHasUploadedAFileWithContentTo()
    When user "Alice" moves folder "<folder_name>" to "/uploadFolder" using the WebDAV API                                        # FeatureContext::userMovesFileUsingTheAPI()
    Then the HTTP status code should be "201"                                                                                     # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the content of file "/uploadFolder/abc.txt" for user "Alice" should be "uploaded content for file name ending with a dot" # FeatureContext::contentOfFileForUserShouldBe()

    Examples:
      | dav_version | folder_name   |
      | old         | /upload.      |
      | old         | /upload.1     |
      | old         | /upload...1.. |
      | old         | /...          |
      | old         | /..upload     |
      | new         | /upload.      |
        Failed step: And user "Alice" has created folder "/upload."
        HTTP status code was not 201 or 204 while trying to create folder '/upload.' for user 'Alice'
        Failed asserting that an array contains 409.
      | new         | /upload.1     |
      | new         | /upload...1.. |
      | new         | /...          |
      | new         | /..upload     |
      | spaces      | /upload.      |
      | spaces      | /upload.1     |
      | spaces      | /upload...1.. |
      | spaces      | /...          |
      | spaces      | /..upload     |
```

### PR DESCRIPTION
**Pull request by ghost**
## Description

Refactored the code so that when a response of an API request is `409` it retries 10 times 

## Related Issue

- Fixes https://github.com/owncloud/ocis/issues/6630

## How Has This Been Tested?

- test environment:
- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

File: tests/TestHelpers/HttpRequestHelper.php [hunk 1]
```diff
@@ -216,17 +216,17 @@ public static function sendRequest(
...
 			}
 			$sendCount = $sendCount + 1;
-			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY) && ($sendCount <= $sendRetryLimit);
+			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY || $response->getStatusCode() === self::HTTP_CONFLICT) && $sendCount <= $sendRetryLimit;
 			if ($loopAgain) {
-				// we need to repeat the send request, because we got HTTP_TOO_EARLY
+				// we need to repeat the send request, because we got HTTP_TOO_EARLY or HTTP_CONFLICT
 				// wait 1 second before sending again, to give the server some time
 				// to finish whatever post-processing it might be doing.
 				\sleep(1);
```
Comment (nirajacharya2) [inline tests/TestHelpers/HttpRequestHelper.php:232]: since we are getting `409` in CI only giving the response and message might be helpful for debugging and understanding the actual behaviour
```suggestion
				// to finish whatever post-processing it might be doing.
				if(409){
				        give response
				}
				\sleep(1);
```

File: tests/TestHelpers/HttpRequestHelper.php [hunk 2]
```diff
@@ -216,17 +216,17 @@ public static function sendRequest(
...
+			if ($response->getStatusCode() >= 400 && $response->getStatusCode() !== self::HTTP_TOO_EARLY && $response->getStatusCode() !== self::HTTP_CONFLICT) {
 				$sendExceptionHappened = true;
 			}
 
 			if ($debugResponses) {
 				self::debugResponse($response);
 			}
 			$sendCount = $sendCount + 1;
-			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY) && ($sendCount <= $sendRetryLimit);
+			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY || $response->getStatusCode() === self::HTTP_CONFLICT) && $sendCount <= $sendRetryLimit;
```
Comment (nirajacharya2) [inline tests/TestHelpers/HttpRequestHelper.php:227]: currently this function has 47 usages but we only need to loop this when we get `409` while making a folder so i think we should destructure this into 
```suggestion
                        $sendExceptionConflictHappened = false;
			if ($response->getStatusCode() >= 400 && $response->getStatusCode() !== self::HTTP_TOO_EARLY && $response->getStatusCode() !== self::HTTP_CONFLICT) {
				$sendExceptionHappened = true;
			}

            if ($response->getStatusCode() === self::HTTP_CONFLICT && substr($url,44)==="https://localhost:9200/remote.php/dav/files/") {
                $sendExceptionConflictHappened = true;
            }

			if ($debugResponses) {
				self::debugResponse($response);
			}
			$sendCount = $sendCount + 1;
			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY || $response->getStatusCode() === self::HTTP_CONFLICT) && $sendCount <= $sendRetryLimit;
            $loopAgainConflict = !$sendExceptionConflictHappened && $sendCount <= $sendRetryLimit;
			if ($loopAgain || $loopAgainConflict) {
				// we need to repeat the send request, because we got HTTP_TOO_EARLY or HTTP_CONFLICT
				// wait 1 second before sending again, to give the server some time
				// to finish whatever post-processing it might be doing.
				\sleep(1);
```

File: tests/TestHelpers/HttpRequestHelper.php [hunk 3]
```diff
@@ -216,17 +217,20 @@ public static function sendRequest(
...
 			}
 
 			if ($debugResponses) {
 				self::debugResponse($response);
 			}
 			$sendCount = $sendCount + 1;
-			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY) && ($sendCount <= $sendRetryLimit);
+			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY ||
+						($response->getStatusCode() === self::HTTP_CONFLICT &&
+						substr($url, 0, 44) ===self::MAKE_FOLDER_API)) &&
```
Comment (nirajacharya2) [inline tests/TestHelpers/HttpRequestHelper.php:230]: currently this function has 47 usages but we only need to loop this when we get `409` making a folder so i think we should check for it hear rather than sending a flag from functions to function. or i can change it.

File: tests/TestHelpers/HttpRequestHelper.php [hunk 4]
```diff
@@ -216,17 +217,20 @@ public static function sendRequest(
...
 			}
 
 			if ($debugResponses) {
 				self::debugResponse($response);
 			}
 			$sendCount = $sendCount + 1;
-			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY) && ($sendCount <= $sendRetryLimit);
+			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY ||
+						($response->getStatusCode() === self::HTTP_CONFLICT &&
+						substr($url, 0, 44) === self::MAKE_FOLDER_API)) &&
```
Comment (nirajacharya2) [inline tests/TestHelpers/HttpRequestHelper.php:230]: currently this function has 47 usages but we only need to loop this when we get `409` while making a folder. so i think we should check for it hear rather than sending a flag from functions to function. or i can change it.
```suggestion
						($response->getStatusCode() === self::HTTP_CONFLICT &&
						substr($url, 0, 44) === self::MAKE_FOLDER_API)) &&
```

Comment (phil-davis) [reply tests/TestHelpers/HttpRequestHelper.php:230]: We think that there can be very short race-conditions when a user is first created and then a folder (or file?) is created/uploaded "immediately". A `409` conflict response can be returned. Presumably there is some backend processing still finishing for the user creation, and the quickly-incoming request "thinks" that the user does not exist and returns a `409`.

In "normal" `When` and `Then` steps we probably do not want to retry - if we get a `409` response then we want to send that back to the test code, and it will decide what to do (probably a `Then` step will fail that is expecting a `2xx` response code).

So we need a way to know that the request is for a `Given` step that is creating a folder, or uploading a file. Those are the times when this "transient" `409` might happen and be OK to retry.

If we can think of some way to "calculate" from the parameters passed to `sendRequest()` and know if it is a folder create or file upload from  `Given` step, then we can do that. Otherwise, we will have to pass a flag down to `sendRequest()`. Note: the flag can have default `false` and so only the functions that actually need to pass it through or set it `true` need to be modified.

File: tests/TestHelpers/HttpRequestHelper.php [hunk 5]
```diff
@@ -41,7 +41,8 @@
  */
 class HttpRequestHelper {
 	public const HTTP_TOO_EARLY = 425;
-
+	public const HTTP_CONFLICT = 409;
+	public const MAKE_FOLDER_API = "https://localhost:9200/remote.php/dav/files/";
```
Comment (saw-jan) [inline tests/TestHelpers/HttpRequestHelper.php:45]: ocis url will be different in different environment

File: tests/TestHelpers/HttpRequestHelper.php (hunk 1 above)
Comment (phil-davis) [reply tests/TestHelpers/HttpRequestHelper.php:236]: Yes, a message will be useful.
It should just be a "warning" or "information" message - the code will keep running and try again.
Normally nobody will see the message anyway, because the test scenario will usually still pass (the retry of the request will probably pass). So nobody will know to look in the drone output. But I don't know how to communicate this sort of information back to the PR - we can't post GitHub comments.

File: tests/TestHelpers/HttpRequestHelper.php (hunk 5 above)
Comment (SwikritiT) [reply tests/TestHelpers/HttpRequestHelper.php:45]: I think there should be a function `getBaseurl` in some helper filer that you can use to construct this

File: tests/TestHelpers/HttpRequestHelper.php [hunk 6]
```diff
@@ -216,19 +218,22 @@ public static function sendRequest(
...
 			}
 
 			if ($debugResponses) {
 				self::debugResponse($response);
 			}
 			$sendCount = $sendCount + 1;
-			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY) && ($sendCount <= $sendRetryLimit);
+			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY ||
+						($response->getStatusCode() === self::HTTP_CONFLICT && $isGivenStep)) &&
+						$sendCount <= $sendRetryLimit;
```
Comment (SagarGi) [inline tests/TestHelpers/HttpRequestHelper.php:231]: can you add some comments regarding the early fail and conflict status code. It might be confusing when someone looks at it. You can add comment what is the reason of doing this for both.

File: tests/TestHelpers/HttpRequestHelper.php [hunk 7]
```diff
@@ -216,19 +218,22 @@ public static function sendRequest(
...
 			if ($loopAgain) {
-				// we need to repeat the send request, because we got HTTP_TOO_EARLY
+				// we need to repeat the send request, because we got HTTP_TOO_EARLY or HTTP_CONFLICT
 				// wait 1 second before sending again, to give the server some time
 				// to finish whatever post-processing it might be doing.
+				echo($response->getBody()->getContents());
```
Comment (SagarGi) [inline tests/TestHelpers/HttpRequestHelper.php:236]: did you for got to remove this echo while debugging or is it part of this PR?

Comment (nirajacharya2) [reply tests/TestHelpers/HttpRequestHelper.php:236]: it is a part of the PR

File: tests/TestHelpers/WebDavHelper.php [hunk 8]
```diff
@@ -623,7 +624,8 @@ public static function makeDavRequest(
 		?int $timeout = 0,
 		?Client $client = null,
 		?array $urlParameter = [],
-		?string $doDavRequestAsUser = null
+		?string $doDavRequestAsUser = null,
+		?bool $isGivenStep=false
```
Comment (phil-davis) [inline tests/TestHelpers/WebDavHelper.php:628]:
```suggestion
		?bool $isGivenStep = false
```

File: tests/acceptance/features/bootstrap/WebDav.php [hunk 9]
```diff
@@ -404,7 +407,8 @@ public function makeDavRequest(
 		bool $stream = false,
 		?string $password = null,
 		?array $urlParameter = [],
-		?string $doDavRequestAsUser = null
+		?string $doDavRequestAsUser = null,
+		?bool $isGivenStep=false
```
Comment (phil-davis) [inline tests/acceptance/features/bootstrap/WebDav.php:411]:
```suggestion
		?bool $isGivenStep = false
```

File: tests/TestHelpers/WebDavHelper.php [hunk 10]
```diff
@@ -601,6 +601,7 @@ public static function getPersonalSpaceIdForUserOrFakeIfNotFound(string $baseUrl
 	 * @param Client|null $client
 	 * @param array|null $urlParameter to concatenate with path
 	 * @param string|null $doDavRequestAsUser run the DAV as this user, if null it is the same as $user
+	 * @param bool $isGivenStep is true if made makeDavRequest from given step
```
Comment (phil-davis) [inline tests/TestHelpers/WebDavHelper.php:604]:
```suggestion
	 * @param bool $isGivenStep is set to true if makeDavRequest is called from a "given" step
```

File: tests/TestHelpers/HttpRequestHelper.php [hunk 11]
```diff
@@ -216,19 +218,23 @@ public static function sendRequest(
...
+			if ($response->getStatusCode() >= 400 && $response->getStatusCode() !== self::HTTP_TOO_EARLY && $response->getStatusCode() !== self::HTTP_CONFLICT) {
 				$sendExceptionHappened = true;
 			}
 
 			if ($debugResponses) {
 				self::debugResponse($response);
 			}
 			$sendCount = $sendCount + 1;
-			$loopAgain = !$sendExceptionHappened && ($response->getStatusCode() === self::HTTP_TOO_EARLY) && ($sendCount <= $sendRetryLimit);
+			// here we check if the response has status code 425 or is a 409 gotten from a Given step
```
Comment (phil-davis) [inline tests/TestHelpers/HttpRequestHelper.php:229]:
```suggestion
			// Here we check if the response has status code 425 or is a 409 gotten from a Given step
			// HTTP_TOO_EARLY (425) can happen if async processing of a previous request is still happening.
			// For example, if a test uploads a file and then immediately tries to download it.
			// HTTP_CONFLICT (409) can happen if the user has just been created in the previous step.
			// The OCS API might not "realize" yet that the user exists. A folder creation (MKCOL) or maybe even
			// a file upload might return 409.
			// In all these cases we can try the API request again after a short time.
```

**Review by phil-davis — COMMENTED** [review]
Just some suggestions about consistent code format, and a suggested long comment explaining the things that we know about that can result in 425 or 409 responses.

**Review by phil-davis — APPROVED** [review]
This looks good - it should protect from unnecessary test fails in the case of user creation followed by folder creation (MKCOL).

After merging this we can think if there are some other Given steps where we should use this protection (Given Alice has uploaded file "xyz.txt", and...?)

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: PR #6835 extends this so that the "retry on 409" also happens for file-upload "Given" steps.
