### PR TITLE
graph: Fix so that accountEnabled updates work for educationUser.

### LINKED ISSUE #5816: graph: Support `accountEnabled` property on education/users/
## Describe the bug

The `accountEnabled` property, while expose on the API is currently no correctly update when PATCHing it via the /education/users endpoint.

### PR DESCRIPTION
**Pull request by Excds**
## Description
Fix so that the accountEnabled attribute will be updated on PATCH requests for educationUser.

## Related Issue
- Fixes #5816 

## How Has This Been Tested?

Tested using curl and updated unit tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

File: services/graph/pkg/identity/ldap.go [hunk 1]
```diff
@@ -1057,3 +1029,32 @@ func (i *LDAP) usersEnabledState(users []*ldap.Entry) (usersEnabledState map[str
...
+		if accountEnabled {
+			err = i.enableUser(logger, e.DN)
+		} else {
+			err = i.disableUser(logger, e.DN)
+		}
+		updateNeeded = true
+	}
+
+	return updateNeeded, err
+}
```
Comment (butonic) [inline services/graph/pkg/identity/ldap.go:1060]: This switch case makes me think that an `i.disableMechanism func(mr *ldap.ModifyRequest, e *ldap.Entry, enabled bool) error` with three different implementations (DisableMechanismNoop, DisableMechanismAttribute and DisableMechanismGroup) that are chosen / configured at initialization would be better to read and extend.

Could you refactor this?

**Review by butonic — APPROVED** [review]
I think a configurable function would make more sense than a switch case statement. Otherwise LGTM. Feel free to merge if you think otherwise.

File: services/graph/pkg/identity/ldap.go (hunk 1 above)
Comment (Excds) [reply services/graph/pkg/identity/ldap.go:1060]: @butonic I don't quite follow what you want me to do. Do you want me to store the function to use on initialization?

Comment (Excds) [reply services/graph/pkg/identity/ldap.go:1060]: Discussed with Ralf and we came to the conclusion that this can be done later.
