### PR TITLE
[tests-only][full-ci] api test to get personal drive information of other users

### LINKED ISSUE #6017: Admin user trying to get the personal drive information of other users returns 404
## Describe the bug

When admin user tries to get the personal drive information of other users using the endpoint `/graph/v1.0/users/{userid}/drive`, then the returned status code is `404`.

## Steps to reproduce

1. Create users `Alice` and `Brian`
2. Assign `Alice` the role `Admin`
3. `Alice` tries to get the drive information of `Brian` using the endpoint `/graph/v1.0/users/{userid}/drive`

## Actual Behavior
The returned status code is `404`.
```
> GET /graph/v1.0/users/4c510ada-c86b-4815-8820-42cdf82c3d51/drive HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.81.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Length: 177
< Content-Security-Policy: frame-ancestors 'none'
< Content-Type: application/json; charset=utf-8
< Date: Wed, 12 Apr 2023 08:30:50 GMT
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Graph-Version: 3.0.0-alpha.2+0e2d20fe6
```

## Expected Behavior
The returned status code should be `200`. And the response should contain the personal drive information of user `Brian`.

### PR DESCRIPTION
**Pull request by PrajwolAmatya**
## Description
This PR adds the api test to get the personal drive information of users by admin or non-admin users using endpoint `/graph/v1.0/users/{userid}/drive`.

## Related Issue

Closes https://github.com/owncloud/ocis/issues/6011
Fixes #6017

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
E2E tests failed: https://drone.owncloud.com/owncloud/ocis/21176/88/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/21176/tracing/folder-alice-2023-4-6-06-56-43.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/21176/tracing/folder-brian-2023-4-6-06-56-58.zip 


</p></details>

File: tests/acceptance/features/bootstrap/GraphContext.php [hunk 1]
```diff
@@ -2256,4 +2256,28 @@ public function theUsersShouldBeListedOnceToAGroup(string $user, string $group):
 			"Expected user '" . $user . "' to be added once to group '" . $group . "' but the user is listed '" . $count . "' times"
 		);
 	}
+
+	/**
+	 * @When /^the user "([^"]*)" gets user "([^"]*)" along with his personal drive information using Graph API$/
+	 * @When /^the user "([^"]*)" gets his personal drive information using Graph API$/
```
Comment (SagarGi) [inline tests/acceptance/features/bootstrap/GraphContext.php:2262]:
```suggestion
	 * @When /^the user "([^"]*)" gets user "([^"]*)" along with (his|her) personal drive information using Graph API$/
	 * @When /^the user "([^"]*)" gets (his|her) personal drive information using Graph API$/
```

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 2]
```diff
@@ -1005,3 +1005,223 @@ Feature: get users
       | Guest       | User        |
       | Guest       | Guest       |
       | Guest       | Admin       |
+
+  @issue-6017
+  Scenario Outline: admin user gets the drive information of a user with different user role
+    Given the administrator has given "Alice" the role "Admin" using the settings api
+    And the administrator has given "Brian" the role "<userRole>" using the settings api
+    When the user "Alice" gets user "Brian" along with his personal drive information using Graph API
```
Comment (saw-jan) [inline tests/acceptance/features/apiGraph/getUser.feature:1013]:
```suggestion
    When user "Alice" gets the personal drive information of user "Brian" using Graph API
```

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 3]
```diff
@@ -1005,3 +1005,223 @@ Feature: get users
...
+      | Admin       |
+      | Space Admin |
+      | User        |
+      | Guest       |
+
+
+  Scenario Outline: non-admin user tries to get drive information of other user with different user role
+    Given the administrator has given "Alice" the role "<user-role>" using the settings api
+    And the administrator has given "Brian" the role "<userRole>" using the settings api
+    When the user "Alice" gets user "Brian" along with his personal drive information using Graph API
```
Comment (SagarGi) [inline tests/acceptance/features/apiGraph/getUser.feature:1113]: if i am not wrong the API endpoint only retrieves the personal drive information right?  if so then the step name and the scenario name can be adjust accordingly.

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 4]
```diff
@@ -1005,3 +1005,223 @@ Feature: get users
...
+      | User        | Guest       |
+      | Guest       | Admin       |
+      | Guest       | Space Admin |
+      | Guest       | User        |
+      | Guest       | Guest       |
+
+
+  Scenario Outline: user gets his/her own drive information with different user role
+    Given the administrator has given "Alice" the role "<userRole>" using the settings api
+    When the user "Alice" gets his personal drive information using Graph API
```
Comment (saw-jan) [inline tests/acceptance/features/apiGraph/getUser.feature:1133]:
```suggestion
    When user "Alice" gets the personal drive information using Graph API
```

File: tests/TestHelpers/GraphHelper.php [hunk 5]
```diff
@@ -345,6 +345,32 @@ public static function getUserWithDriveInformation(
...
+	 * @param string $baseUrl
+	 * @param string $xRequestId
+	 * @param string $byUser
+	 * @param string $userPassword
+	 * @param string $userId
+	 *
+	 * @return ResponseInterface
+	 * @throws GuzzleException
+	 */
+	public static function getUserWithDriveInformationByUserId(
```
Comment (saw-jan) [inline tests/TestHelpers/GraphHelper.php:358]:
```suggestion
	public static function getPersonalDriveInformationByUserId(
```

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 6]
```diff
@@ -1005,3 +1005,223 @@ Feature: get users
...
+      | User        | Guest       |
+      | Guest       | Admin       |
+      | Guest       | Space Admin |
+      | Guest       | User        |
+      | Guest       | Guest       |
+
+
+  Scenario Outline: user with different user role gets his/her own drive information
+    Given the administrator has assigned the role "<userRole>" to user "Alice" using the Graph API
+    When user "Alice" gets the personal drive information using Graph API
```
Comment (SagarGi) [inline tests/acceptance/features/apiGraph/getUser.feature:1133]:
```suggestion
    When user "Alice" gets own personal drive information using Graph API
```
if we could do something like this? since alice is getting his own information right?

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 7]
```diff
@@ -1005,3 +1005,223 @@ Feature: get users
...
+      | Space Admin |
+      | User        |
+      | Guest       |
+
+
+  Scenario Outline: non-admin user tries to get drive information of other user with different user role
+    Given the administrator has given "Alice" the role "<user-role>" using the settings api
+    And the administrator has given "Brian" the role "<userRole>" using the settings api
+    When user "Alice" gets the personal drive information of user "Brian" using Graph API
+    Then the HTTP status code should be "404"
```
[the remark this answers is not in the document]
Comment (saw-jan) [reply tests/acceptance/features/apiGraph/getUser.feature:1114]: CC @ScharfViktor

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 8]
```diff
@@ -1005,3 +1005,223 @@ Feature: get users
       | Guest       | User        |
       | Guest       | Guest       |
       | Guest       | Admin       |
+
+  @issue-6017
+  Scenario Outline: admin user gets the drive information of a user with different user role
+    Given the administrator has given "Alice" the role "Admin" using the settings api
+    And the administrator has given "Brian" the role "<userRole>" using the settings api
```
[the remark this answers is not in the document]
Comment (ScharfViktor) [reply tests/acceptance/features/apiGraph/getUser.feature]: yes, I agree with the suggestion.  I think we need change it in another feature files too, of course in the another PR

File: tests/acceptance/features/apiGraph/getUser.feature (hunk 7 above)
[the remark this answers is not in the document]
Comment (ScharfViktor) [reply tests/acceptance/features/apiGraph/getUser.feature:1114]: 404 based on the comment https://github.com/owncloud/ocis/pull/5742#issuecomment-1482547906

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 9]
```diff
@@ -1005,3 +1005,223 @@ Feature: get users
       | Guest       | User        |
       | Guest       | Guest       |
       | Guest       | Admin       |
+
+  @issue-6017
+  Scenario Outline: admin user gets the drive information of a user with different user role
+    Given the administrator has assigned the role "Admin" to user "Alice" using the Graph API
+    And the administrator has assigned the role "<userRole>" to user "Brian" using the Graph API
+    When user "Alice" gets the personal drive information of user "Brian" using Graph API
```
Comment (ScharfViktor) [inline tests/acceptance/features/apiGraph/getUser.feature:1013]: before when action -> Brian should logs in to create personal space.
Put please whatever step for Brian

**Comment by ScharfViktor** [comment]
https://github.com/owncloud/ocis/issues/6017 still relevant or can we close?

**Comment by PrajwolAmatya** [comment]
> #6017 still relevant or can we close?

The issue is still there. Even though Brian logs in the returned status code is `404`.
@ScharfViktor

**Review by ScharfViktor — APPROVED** [review]
LGTM

File: tests/acceptance/features/apiGraph/getUser.feature [hunk 10]
```diff
@@ -1005,3 +1005,224 @@ Feature: get users
...
+      | Guest       |
+
+
+  Scenario Outline: non-admin user tries to get drive information of other user with different user role
+    Given the administrator has assigned the role "<user-role>" to user "Alice" using the Graph API
+    And the administrator has assigned the role "<userRole>" to user "Brian" using the Graph API
+    When user "Alice" gets the personal drive information of user "Brian" using Graph API
+    Then the HTTP status code should be "404"
+    Examples:
+      | user-role   | userRole    |
```
Comment (SwikritiT) [inline tests/acceptance/features/apiGraph/getUser.feature:1117]: Can we do it something like this? 
```suggestion
      | user-role-1   | user-role-2    |
```

**Review by SwikritiT — COMMENTED** [review]
Other than the above small comment LGTM. Also please make sure to rebase the branch seems to be little bit behind in commits

File: tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md [hunk 11]
```diff
@@ -170,5 +170,11 @@ The expected failures in this file are from features in the owncloud/ocis repo.
 ### [Adding the same user as multiple members in a single request results in listing the same user twice in the group](https://github.com/owncloud/ocis/issues/5855)
 - [apiGraph/addUserToGroup.feature:407](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/addUserToGroup.feature#L407)
 
+### [Admin user trying to get the personal drive information of other users returns 404](https://github.com/owncloud/ocis/issues/6017)
+- [apiGraph/getUser.feature:1105](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/getUser.feature#L1105)
+- [apiGraph/getUser.feature:1106](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/getUser.feature#L1106)
+- [apiGraph/getUser.feature:1107](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/getUser.feature#L1107)
+- [apiGraph/getUser.feature:1108](https://github.com/owncloud/ocis/blob/master/tests/acceptance/features/apiGraph/getUser.feature#L1108)
```
Comment (saw-jan) [inline tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md:177]: @ScharfViktor @micbar Should we wait for the fix instead of adding tests in expected failure list?

Comment (micbar) [reply tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md:177]: yes, we need the fix right on this branch.

Comment (micbar) [reply tests/acceptance/expected-failures-localAPI-on-OCIS-storage.md:177]: added a commit with the fix.

**Comment by micbar** [comment]
@PrajwolAmatya @ScharfViktor @individual-it What is the test expectation regarding "Space Admin" Roles?

IMO this should behave the same like for users with the "Admin" role.

**Comment by ScharfViktor** [comment]
> @PrajwolAmatya @ScharfViktor @individual-it What is the test expectation regarding "Space Admin" Roles?
> 
> IMO this should behave the same like for users with the "Admin" role.

I think that expectation for "Space Admin" should be `200` and according this tests tests/acceptance/features/apiSpaces/spaceManagement.feature "Space Admin" can see personal space of users  

@PrajwolAmatya please change expectation here
image

**Comment by saw-jan** [comment]
> @PrajwolAmatya @ScharfViktor @individual-it What is the test expectation regarding "Space Admin" Roles?

In test, we are expecting that `Space Admin` user cannot view the other user's personal drive information. (i.e. expecting `404`)

> IMO this should behave the same like for users with the "Admin" role.

If `Space Admin` user should behave like `Admin` user then we need to change the test expectation (from `404` to `200`), which means `Space Admin` can view other users' personal drive information.

**Review by SwikritiT — COMMENTED** [review]
LGTM

**Review by SwikritiT — APPROVED** [review]

**Review by saw-jan — APPROVED** [review]

**Comment by SwikritiT** [comment]
`This branch is 3 commits ahead, 46 commits behind master.`
@PrajwolAmatya please rebase once and then merge
