### PR TITLE
Delete group memberships when deleting a user

### LINKED ISSUE #3027: graph user management: deleting a user doesn't remove group membership
## Describe the bug

(This is when using the LDAP backend of the Graph API)

When deleting a user, we don't yet cleanup the user's groupmember ship in the LDAP server. As LDAP doesn't make any promises about referential integrity we should explicitly remove the user from the groups it was member of.

### PR DESCRIPTION
**Pull request by rhafer**
## Description

Upon deleting a User from the LDAP backend, we also need to cleanup
the user's group memberships as LDAP itself doesn't make any promises
about referential integrity.

## Related Issue
- Fixes #3027

### CODE REVIEW

**Review by C0rby — APPROVED** [review]
~~LGTM~~ Approved to soon.

File: graph/pkg/identity/ldap.go [hunk 1]
```diff
@@ -182,6 +182,20 @@ func (i *LDAP) DeleteUser(ctx context.Context, nameOrID string) error {
 	if err = i.conn.Del(&dr); err != nil {
 		return err
 	}
+
+	// Find all the groups that this user was a member of and remove it from there
+	groupEntries, err := i.getLDAPGroupsByFilter(fmt.Sprintf("(%s=%s)", i.groupAttributeMap.member, e.DN), true, false)
```
Comment (C0rby) [inline graph/pkg/identity/ldap.go:187]: This error needs to be checked.

**Review by C0rby — CHANGES_REQUESTED** [review]

File: graph/pkg/identity/ldap.go (hunk 1 above)
Comment (rhafer) [reply graph/pkg/identity/ldap.go:187]: Fixed.

**Review by C0rby — APPROVED** [review]
