### PR TITLE
do not send www-authenticate basic for Api requests

### LINKED ISSUE #5986: Wrong `WWW-Authenticate: Basic ...` header with basic auth being disabled
## Describe the bug
The `authentication` middleware seems to wrongfully add a `WWW-Authenticate: Basic ...` header in some situations. The code reads like that should only ever exist if basic auth is enabled. But I managed to get some edge cases responses with a 401 and both `WWW-Authenticate: Basic ...` and `WWW-Authenticate: Bearer ...` headers.

### Steps to reproduce
Just run the following curl agains an ocis instance running on `https://host.docker.internal:9200` (or change the URL respectively). 

```
curl 'https://host.docker.internal:9200/ocs/v2.php/apps/notifications/api/v1/notifications?format=json' \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Referer: https://host.docker.internal:9200/files/spaces/personal/admin?fileId=1284d238-aa92-42ce-bdc4-0b0000009157%24some-admin-user-id-0000-000000000000%21some-admin-user-id-0000-000000000000&items-per-page=100&view-mode=resource-table&tiles-size=1' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36' \
  -H 'accept-language: en' \
  -H 'authorization: Bearer eyJhbGciOiJQUzI1NiIsImtpZCI6InByaXZhdGUta2V5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJ3ZWIiLCJleHAiOjE2ODAyNzY0MDQsImlhdCI6MTY4MDI3NjMzNCwiaXNzIjoiaHR0cHM6Ly9ob3N0LmRvY2tlci5pbnRlcm5hbDo5MjAwIiwianRpIjoiel9kYTRXeVNEaVk3TzYyTDR3eGltZ2VlbEkyMTg5NHkiLCJsZy5pIjp7ImRuIjoiQWRtaW4iLCJpZCI6InVpZD1hZG1pbixvdT11c2VycyxvPWxpYnJlZ3JhcGgtaWRtIiwidW4iOiJhZG1pbiJ9LCJsZy5wIjoiaWRlbnRpZmllci1sZGFwIiwibGcudCI6IjEiLCJzY3AiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInN1YiI6InZuMDQ3WURFb0pkYkZIUTdAeDBvOEFqZ2VCOHZhRUs4TTVyRDFuSVIzNTlhVVZLUlhzWThMU1NPQ3pWXzhySndST2lmUVFBbjlQeEJ4Z29tSmxtUE5FUSJ9.I9umYoI3IVoDGQNlXNiwI1YN8WnJPIuSJOMFykQxpzLraPAli6EPquyGzdjaTySeBbzzbU3OFvE0mR8b--3fknWNUV8M0e54e-SS2vt008xPzD97NEKF2j8QyoFO7To6Nrzc3TtpFV4qIo8NOz7CWt4ali2r8ETmlQr0j1bonMgE_twY_wCeS46iaA06EkyXVeCEOL9JBsUEDcBrRhy93ydWDTBcC3UzmeIAh5PAimemwn-bDaw9S9seI3TEBwSgOs5GE_xCgkXcpoCd5RCt7OOlkhN1gNf1n9kt35CDv3BBr5QlRZB9vEeqAbEXQjJkslKuTMZtQ6YIyjEebmp1lzmxD00w3GUBuEpruUJJfC2wDzTAPqqERAaZ91a7jCNSK_vB17Yfv4Vffip4MXCCnAyF_Hz0zyITedNRuw29Mk6frlzgcLCQWZPuSIydxB6bJnv1c-sfiLRGC9gBm1QIsH6Jl0H6ZyUa-c9eK38pG9r2YZflpwaw-N5co0weh_-k00YtYRj0y-fT3FCyU-QgJIO2AuLs5WNQg33nQaeHNFEGyA3YWn2fHoDJHeaWQQo7i02b37i4vmZwYfYNbMkIlETyAXe3X_MdNmBttE7zmX0AerEhvw4FtKDsZEK9o45xc0Qqa5OA2CjVb9tztypsgMjBifRAYogVq8ToIDgSPaI' \
  -H 'ocs-apirequest: true' \
  -H 'sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'x-request-id: 2424e1a6-b305-4bfe-b956-12c93bc7e3dc' \
  -H 'x-requested-with: XMLHttpRequest' \
  --compressed \
  --insecure
```

Since the access token is already expired, ocis returns:

```
> x-requested-with: XMLHttpRequest
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Www-Authenticate: Bearer realm="host.docker.internal:9200", charset="UTF-8"
< Www-Authenticate: Basic realm="host.docker.internal:9200", charset="UTF-8"
```

It should just have failed silently with a 401 and `< Www-Authenticate: Bearer realm="host.docker.internal:9200", charset="UTF-8"`. The `< Www-Authenticate: Basic realm="host.docker.internal:9200", charset="UTF-8"` is wrong and results in the browser showing a basic auth popup. Which is awful user experience. :-(

## How is this relevant
The rare edge case that I had was that the notification request was started in between some token renewal related requests. It seems like the internal idp or some middleware invalidates the access token as soon as a new one is requested. That seems to be totally fishy. I suppose this is not an edge case when you have a few thousand users in a system. That's just bad timing / a race condition that we don't want to have.

In the wild this will likely only ever happen with a scheduled notification listing request being badly timed in the middle of token renewal. Still, in production environments this will happen on a not so frequent but regular basis.

### PR DESCRIPTION
**Pull request by micbar**
## Description

Bugfix: Fix authenticate headers for API requests

We changed the www-authenticate header which should not be sent for "basic-auth" when the `XMLHttpRequest` header is set.

## Related Issue

Fixes #5986 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance test [<strong>wopiValidatorTests-ocis</strong>](https://drone.owncloud.com/owncloud/ocis/21036/47/1) failed. Further test are cancelled...

**Review by dschmidt — COMMENTED** [review]
Thanks for tackling this!

Just a few comments/questsions:
a) Why is this only relevent for basic auth? 
b) The header is `X-Requested-With` and the value is `XmlHttpRequest`
c) There is no regression test :trollface:

**Comment by micbar** [comment]
> a) Why is this only relevent for basic auth?
I am aware that the desktop client always checks the presence of the Www-authenticate header for `bearer` auth.

But we can completely not show any www-authenticate headers if ok for the clients.

> b) The header is X-Requested-With and the value is XmlHttpRequest

Thanks. Will fix

> c) we can do an API test. Let us tackle that separately.

File: services/proxy/pkg/middleware/authentication.go [hunk 1]
```diff
@@ -147,7 +147,9 @@ func configureSupportedChallenges(options Options) {
 func writeSupportedAuthenticateHeader(w http.ResponseWriter, r *http.Request) {
 	caser := cases.Title(language.Und)
 	for _, s := range SupportedAuthStrategies {
-		w.Header().Add(WwwAuthenticate, fmt.Sprintf("%v realm=\"%s\", charset=\"UTF-8\"", caser.String(s), r.Host))
+		if !(s == "basic" && r.Header.Get("XmlHttpRequest") != "") {
```
Comment (kobergj) [inline services/proxy/pkg/middleware/authentication.go:150]: Something is odd with this condition. I still see the `Basic` and the `Bearer` auth header when running the curl from the ticket.

**Review by kobergj — CHANGES_REQUESTED** [review]

**Comment by dschmidt** [comment]
> > a) Why is this only relevent for basic auth?
> I am aware that the desktop client always checks the presence of the Www-authenticate header for `bearer` auth.
> 
> But we can completely not show any www-authenticate headers if ok for the clients.

Ah, interesting - from oC Web prespective: the `www-authenticate` header triggers a super annoying auth popup which we cannot surpress, so it would be great to avoid it completely ... and we don't use basic auth, so basically doing the check only for basic auth it kind of defeats the purpose of the issue we raised in the first place.

 > > b) The header is X-Requested-With and the value is XmlHttpRequest
> 
> Thanks. Will fix

💪🏻 

>  c) we can do an API test. Let us tackle that separately.

Yup, fine with me - I would just highly appreciate a regression test as it's so annoying in oC Web if for whatever reason a token refresh fails or some other condition leads to invalid tokens

File: services/proxy/pkg/middleware/authentication.go (hunk 1 above)
Comment (micbar) [reply services/proxy/pkg/middleware/authentication.go]: fixed it.

**Review by dschmidt — APPROVED** [review]

**Comment by micbar** [comment]
> Now I get no `Www-Authenticate` header at all. Not `Basic` and also not `Bearer`.
> 
> Is this the intended behaviour?

If you are sending `'x-requested-with: XMLHttpRequest' ` you should not get any `Www-Authenticate` header at all.

**Review by kobergj — APPROVED** [review]
